[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.pdo_mysql", "php82Extensions.pdo_sqlite", "php82Extensions.mbstring", "php82Extensions.zip", "php82Packages.composer", "nodejs_20"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[start]
cmd = "touch database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan config:clear && php artisan route:clear && php artisan view:clear && php -S 0.0.0.0:$PORT -t public/"
